name: fast_mvvm
description: Implemented using the MVVM architecture, quickly build projects to help consumers focus only on the business implementation
version: 2.1.2
homepage: https://github.com/StrangerKjq/fast_mvvm

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  https://pub.flutter-io.cn/packages/provider
  provider: ^6.0.3

  # https://pub.flutter-io.cn/packages/dio
  dio: ^4.0.6

  fast_event_bus: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec优化

# The following section is specific to Flutter.
flutter: